twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : /camera_cmd_vel
        timeout : 0.5
        priority: 10
      joystick:
        topic   : /joystick_cmd_vel
        timeout : 0.5
        priority: 100

